
name: Execute python script  # name this workflow 

on:    # When trigger this workflow
  push:    # When a push is made to filtered branch, the event runs.
    branches: [ "master" ]    # filter branches
  schedule:    # set a time to automatically run the task
    - cron: '*/5 * * * *'    # run every 5 minutes

jobs:    # shows a list of jobs to be worked on
  build_and_exeute:    # name one of the jobs
    runs-on: ubuntu-latest    # decide which virtual machine to run (Ubuntu virtual machine)

    steps:    # distribute the job process
    - uses: actions/checkout@v3    # use a virtual repository called checkout in action
    
    - name: Set up Python    # name the step1
      uses: actions/setup-python@v3    # install Python from actions
      with:
        python-version: 3.x    # indicates the Python version to be installed
        
    - name: Install dependencies    # name the step2
      run: |
        # Process the command in the shell. If there are multiple commands, use '|'.
        python -m pip install --upgrade pip    # upgrade the Python package
        pip freeze > requirements.txt    # install the package in requirements.txt
        pip install -r requirements.txt    # install Python according to the packages in requirements.txt
        
    - name: Run python script    # name the step3
      run: python main.py    # run Python from shell
